### ISSUE TITLE
Feature: Make the background color of the slide toggler a bit lighter in dark mode

### ISSUE THREAD

**Issue by monacodelisa** [TechOpenSolve/TechOpenSolve#32]
### Type of feature

✨ Feature

### Current behavior

The slide toggle theme switcher's background color is a bit too dark
- it is hard to see since it blends with the toolbar background color 

![image](https://github.com/TechOpenSolve/TechOpenSolve/assets/64324417/8d93a753-fcad-4bd0-b50d-95f6de266bd3)

### Suggested solution

- make the background color of the theme switcher a bit lighter
- something like this 

![image](https://github.com/TechOpenSolve/TechOpenSolve/assets/64324417/3320148a-9124-4dfb-b9cc-d53b9462becb)

`#2e3a3a`

### Additional context

- must find the correct style for the correct element 

### I would be willing to submit a PR to fix this issue

- [X] Yes and I have read the [Contribution Guide]() and I agree to follow this project's [Code of Conduct]()
- [ ] No

**Comment by SandipGyawali** [comment]
hey @monacodelisa i wanna work can you assign it to me ??

**Comment by monacodelisa** [comment]
@SandipGyawali sure, assigned
